[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[prune]
  go-tests = true
  unused-packages = true
